name: Versus app Image CI
on:
  push:
    branches:
      - feauture/**
      - staging
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
env:
  AWS_REGION: "us-east-1"
  ENVIRONMENT_STAGE: ${{ (github.ref == 'refs/heads/main') && 'production') || (github.ref == 'refs/heads/staging') && 'staging' || (github.ref == 'refs/heads/feature/**' && 'dev')}}
jobs:
  app-build-and-deploy:
    environment: ${{ env.ENVIRONMENT_STAGE }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        if: github.ref != 'refs/heads/main'
        uses: aws-actions/amazon-ecr-login@v1 
        with:
          registry: ${{ secrets.AWS_ECR_REGISTRY }}
